### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Qixingchen** [Qixingchen/CarSharingAll#1]
- [ ] 二步认证体系 密码盐 基于用户密钥摘要的加密 HTTP/SSL
- [ ] 完成出租车拼车，拼货功能
- [ ] 多设备同步功能
- [ ] 性能优化
  - [ ] SparseArray替代HashMap  http://liuzhichao.com/p/832.html
  - [ ] JsonObjectRequest替代 StringRequest  http://blog.csdn.net/guolin_blog/article/details/17482095
  - [ ]
